import 'dart:ui';

import 'package:get/get.dart';

class AppTranslations extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
    Locale('ja'),
    Locale('de'),
    Locale('ru'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('id'),
    Locale('zh'),
    Locale('ar'),
  ];

  @override
  Map<String, Map<String, String>> get keys => const {
    // English
    'en': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Start',
      'stop': 'Stop',
      'settings': 'Settings',
      'history': 'History',
      'no_history': 'No local history yet',
      'sensor_unavailable': 'Sensor unavailable on this device',
      'policy_note':
          'For entertainment and local use only. Detection is not guaranteed.',
      'armed': 'Armed - watching for motion',
      'arming': 'Arming... stay still',
      'alarm_active': 'Motion Detected!',
      'idle': 'Ready to arm',
      'stop_alarm': 'Stop Alarm',
      'delta': 'Delta',
      'delay_label': 'Delay: @ns',
      'sensitivity': 'Sensitivity',
      'sensitivity_low': 'Low',
      'sensitivity_medium': 'Medium',
      'sensitivity_high': 'High',
      'sensitivity_low_desc': 'Triggers only on a strong push or pickup',
      'sensitivity_medium_desc': 'Balanced — reacts to a normal nudge',
      'sensitivity_high_desc': 'Reacts to the slightest touch or vibration',
      'arm': 'Arm',
      'disarm': 'Disarm',
      'dismiss_alarm': 'Dismiss Alarm',
      'state_disarmed': 'DISARMED',
      'state_arming': 'ARMING',
      'state_armed': 'ARMED',
      'state_alarm': 'ALARM',
      'dial_hint_disarmed': 'Tap to arm',
      'dial_hint_arming': 'Keep the phone still',
      'dial_hint_armed': 'Watching for motion',
      'dial_hint_alarm': 'Tap below to dismiss',
      'retry': 'Retry',
      'sensor_retry_hint': 'Tap Arm to try again',
      'alarm_sound': 'Alarm sound',
      'sound_siren': 'Siren',
      'sound_beep': 'Beep',
      'more_settings': 'More',
      'detection_section': 'Detection',
      'alarm_section': 'Alarm',
      'about_section': 'About',
      'delay_desc': 'Time to place the phone before arming',
      'haptics': 'Vibration',
      'haptics_desc': 'Vibrate the phone while the alarm sounds',
      'test_alarm': 'Test alarm',
      'settings_locked': 'Stop the session to change these settings',
      'version': 'Version',
      'popular': 'Popular',
      'motion_detected': 'Motion detected',
      'delta_value': 'Delta @n',
      'how_to_use': 'How to Use',
      'step_settings': 'Set delay and sensitivity',
      'step_place': 'Tap Start, then keep the phone still',
      'step_stop': 'Stop the session yourself to silence',
      'onboarding_skip': 'Skip',
      'onboarding_next': 'Next',
      'onboarding_get_started': 'Get Started',
      'onboarding_intro_title': 'Pocket motion alarm',
      'onboarding_intro_desc':
          'Detects movement and sounds an alarm when someone touches your bag or phone.',
      'onboarding_how_title': 'Set delay and sensitivity',
      'onboarding_how_desc':
          'Choose how long to wait before arming and how sensitive motion detection should be.',
      'onboarding_ready_title': 'Ready to guard',
      'onboarding_ready_desc':
          'Place the phone, tap Start, and the alarm watches for movement.',
      'onboarding_privacy_note':
          'Runs fully on-device. No account or special permissions.',
      'premium': 'Premium',
      'premium_title': 'Support the App',
      'premium_subtitle': 'Remove ads with a one-time tip',
      'premium_unlocked': 'Premium active. Thank you!',
      'premium_purchase': 'Get Premium',
      'premium_restore': 'Restore purchase',
      'premium_loading': 'Loading...',
      'premium_store_unavailable': 'Store unavailable',
      'premium_option_small_title': 'Coffee Tip',
      'premium_option_small_desc': 'Remove ads',
      'premium_option_medium_title': 'Lunch Treat',
      'premium_option_medium_desc': 'Remove ads (most popular)',
      'premium_option_large_title': 'Full Support',
      'premium_option_large_desc': 'Remove ads + thank you!',
      'premium_benefit_no_ads': 'No Ads',
      'premium_benefit_no_ads_desc': 'Enjoy an ad-free experience',
      'premium_benefit_lifetime': 'Lifetime',
      'premium_benefit_lifetime_desc': 'One-time, no subscriptions',
      'premium_benefit_support': 'Support Dev',
      'premium_benefit_support_desc': 'Help keep the app alive',
      'premium_benefit_peace': 'Peace of Mind',
      'premium_benefit_peace_desc': 'Focus on what matters',
      'remove_ads_cta': 'Remove ads · Support developer',
      'premium_one_time_note': 'One-time purchase · No subscription',
      'premium_benefits_title': 'What you get',
    },

    // 한국어
    'ko': {
      'app_title': 'Motion Alarm Pocket',
      'start': '시작',
      'stop': '중지',
      'settings': '설정',
      'history': '기록',
      'no_history': '아직 로컬 기록이 없습니다',
      'sensor_unavailable': '이 기기에서 센서를 사용할 수 없습니다',
      'policy_note': '엔터테인먼트 및 로컬 용도이며 감지를 보장하지 않습니다.',
      'armed': '감시 중 - 움직임을 감지합니다',
      'arming': '준비 중... 폰을 가만히 두세요',
      'alarm_active': '움직임 감지됨!',
      'idle': '시작할 준비 완료',
      'stop_alarm': '경보 중지',
      'delta': '변화량',
      'delay_label': '딜레이: @n초',
      'sensitivity': '감도',
      'sensitivity_low': '낮음',
      'sensitivity_medium': '중간',
      'sensitivity_high': '높음',
      'sensitivity_low_desc': '세게 밀거나 들어 올릴 때만 울립니다',
      'sensitivity_medium_desc': '균형 — 일반적인 흔들림에 반응합니다',
      'sensitivity_high_desc': '아주 작은 접촉이나 진동에도 반응합니다',
      'arm': '감시 시작',
      'disarm': '감시 해제',
      'dismiss_alarm': '경보 끄기',
      'state_disarmed': '해제됨',
      'state_arming': '준비 중',
      'state_armed': '감시 중',
      'state_alarm': '경보',
      'dial_hint_disarmed': '탭하여 시작',
      'dial_hint_arming': '폰을 가만히 두세요',
      'dial_hint_armed': '움직임을 감시 중',
      'dial_hint_alarm': '아래를 탭해 끄기',
      'retry': '다시 시도',
      'sensor_retry_hint': '감시 시작을 눌러 다시 시도하세요',
      'alarm_sound': '경보음',
      'sound_siren': '사이렌',
      'sound_beep': '비프음',
      'more_settings': '더보기',
      'detection_section': '감지',
      'alarm_section': '경보',
      'about_section': '정보',
      'delay_desc': '감시를 시작하기 전 폰을 둘 시간',
      'haptics': '진동',
      'haptics_desc': '경보가 울릴 때 폰을 진동시킵니다',
      'test_alarm': '경보음 테스트',
      'settings_locked': '설정을 변경하려면 세션을 중지하세요',
      'version': '버전',
      'popular': '인기',
      'motion_detected': '움직임 감지',
      'delta_value': '변화량 @n',
      'how_to_use': '사용 방법',
      'step_settings': '딜레이와 감도를 설정하세요',
      'step_place': '시작을 탭한 후 폰을 가만히 두세요',
      'step_stop': '세션을 직접 중지해야 경보가 꺼집니다',
      'onboarding_skip': '건너뛰기',
      'onboarding_next': '다음',
      'onboarding_get_started': '시작하기',
      'onboarding_intro_title': '주머니 속 움직임 알람',
      'onboarding_intro_desc': '가방이나 폰에 누군가 손대면 움직임을 감지해 경보를 울립니다.',
      'onboarding_how_title': '딜레이와 감도 설정',
      'onboarding_how_desc': '감시를 시작하기 전 대기 시간과 움직임 감지 민감도를 선택하세요.',
      'onboarding_ready_title': '감시 준비 완료',
      'onboarding_ready_desc': '폰을 두고 시작을 누르면 알람이 움직임을 감시합니다.',
      'onboarding_privacy_note': '모든 동작은 기기 안에서 처리됩니다. 계정·별도 권한 불필요.',
      'premium': '프리미엄',
      'premium_title': '앱 후원하기',
      'premium_subtitle': '일회성 후원으로 광고를 제거하세요',
      'premium_unlocked': '프리미엄 활성화. 감사합니다!',
      'premium_purchase': '프리미엄 구매',
      'premium_restore': '구매 복원',
      'premium_loading': '로딩 중...',
      'premium_store_unavailable': '스토어를 사용할 수 없습니다',
      'premium_option_small_title': '커피 한 잔',
      'premium_option_small_desc': '광고 제거',
      'premium_option_medium_title': '점심 한 끼',
      'premium_option_medium_desc': '광고 제거 (인기)',
      'premium_option_large_title': '풀 서포트',
      'premium_option_large_desc': '광고 제거 + 감사 인사!',
      'premium_benefit_no_ads': '광고 없음',
      'premium_benefit_no_ads_desc': '광고 없는 경험',
      'premium_benefit_lifetime': '평생 이용',
      'premium_benefit_lifetime_desc': '일회성, 구독 없음',
      'premium_benefit_support': '개발자 후원',
      'premium_benefit_support_desc': '앱 유지에 도움',
      'premium_benefit_peace': '안심 사용',
      'premium_benefit_peace_desc': '중요한 것에 집중',
      'remove_ads_cta': '광고 제거 · 개발자 후원',
      'premium_one_time_note': '일회성 구매 · 구독 없음',
      'premium_benefits_title': '프리미엄 혜택',
    },

    // 日本語
    'ja': {
      'app_title': 'Motion Alarm Pocket',
      'start': '開始',
      'stop': '停止',
      'settings': '設定',
      'history': '履歴',
      'no_history': 'ローカル履歴はまだありません',
      'sensor_unavailable': 'このデバイスではセンサーを使用できません',
      'policy_note': '娯楽およびローカル用途のみです。検知は保証されません。',
      'armed': '監視中 - 動きを確認しています',
      'arming': '準備中... 動かさないでください',
      'alarm_active': '動きを検知しました！',
      'idle': '開始準備完了',
      'stop_alarm': 'アラーム停止',
      'delta': '変化量',
      'delay_label': '遅延: @n秒',
      'sensitivity': '感度',
      'sensitivity_low': '低',
      'sensitivity_medium': '中',
      'sensitivity_high': '高',
      'sensitivity_low_desc': '強く押すか持ち上げたときのみ作動',
      'sensitivity_medium_desc': 'バランス — 普通の揺れに反応します',
      'sensitivity_high_desc': 'わずかな接触や振動にも反応します',
      'arm': '監視開始',
      'disarm': '監視解除',
      'dismiss_alarm': 'アラームを止める',
      'state_disarmed': '解除',
      'state_arming': '準備中',
      'state_armed': '監視中',
      'state_alarm': 'アラーム',
      'dial_hint_disarmed': 'タップで開始',
      'dial_hint_arming': 'スマホを動かさないで',
      'dial_hint_armed': '動きを監視中',
      'dial_hint_alarm': '下をタップして停止',
      'retry': '再試行',
      'sensor_retry_hint': '監視開始を押して再試行',
      'alarm_sound': 'アラーム音',
      'sound_siren': 'サイレン',
      'sound_beep': 'ビープ',
      'more_settings': 'その他',
      'detection_section': '検知',
      'alarm_section': 'アラーム',
      'about_section': '情報',
      'delay_desc': '監視開始前にスマホを置くまでの時間',
      'haptics': 'バイブレーション',
      'haptics_desc': 'アラーム中にスマホを振動させます',
      'test_alarm': 'アラームをテスト',
      'settings_locked': '設定を変更するにはセッションを停止してください',
      'version': 'バージョン',
      'popular': '人気',
      'motion_detected': '動きを検知',
      'delta_value': '変化量 @n',
      'how_to_use': '使い方',
      'step_settings': '遅延と感度を設定します',
      'step_place': '開始をタップし、スマホを静かに置きます',
      'step_stop': '音を止めるには自分でセッションを停止します',
      'onboarding_skip': 'スキップ',
      'onboarding_next': '次へ',
      'onboarding_get_started': '始める',
      'onboarding_intro_title': 'ポケットの動きアラーム',
      'onboarding_intro_desc': 'バッグやスマホに誰かが触れたとき、動きを検知してアラームを鳴らします。',
      'onboarding_how_title': '遅延と感度を設定',
      'onboarding_how_desc': '監視開始までの待ち時間と、動き検知の感度を選べます。',
      'onboarding_ready_title': '見守り準備完了',
      'onboarding_ready_desc': 'スマホを置いて開始をタップすると、アラームが動きを監視します。',
      'onboarding_privacy_note': 'すべて端末内で動作します。アカウントや特別な権限は不要です。',
      'premium': 'プレミアム',
      'premium_title': 'アプリを応援',
      'premium_subtitle': '一度の応援で広告を削除',
      'premium_unlocked': 'プレミアム有効。ありがとうございます！',
      'premium_purchase': 'プレミアムを購入',
      'premium_restore': '購入を復元',
      'premium_loading': '読み込み中...',
      'premium_store_unavailable': 'ストアを利用できません',
      'premium_option_small_title': 'コーヒー応援',
      'premium_option_small_desc': '広告を削除',
      'premium_option_medium_title': 'ランチ応援',
      'premium_option_medium_desc': '広告を削除（人気）',
      'premium_option_large_title': 'フルサポート',
      'premium_option_large_desc': '広告削除 + 感謝！',
      'premium_benefit_no_ads': '広告なし',
      'premium_benefit_no_ads_desc': '広告のない体験',
      'premium_benefit_lifetime': '永久利用',
      'premium_benefit_lifetime_desc': '一度きり、サブスクなし',
      'premium_benefit_support': '開発者を応援',
      'premium_benefit_support_desc': 'アプリの継続に貢献',
      'premium_benefit_peace': '安心',
      'premium_benefit_peace_desc': '大切なことに集中',
      'remove_ads_cta': '広告を削除 · 開発者を応援',
      'premium_one_time_note': '買い切り · サブスクなし',
      'premium_benefits_title': '得られる特典',
    },

    // Deutsch
    'de': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Start',
      'stop': 'Stopp',
      'settings': 'Einstellungen',
      'history': 'Verlauf',
      'no_history': 'Noch kein lokaler Verlauf',
      'sensor_unavailable': 'Sensor auf diesem Gerät nicht verfügbar',
      'policy_note':
          'Nur für Unterhaltung und lokale Nutzung. Erkennung ist nicht garantiert.',
      'armed': 'Scharf - überwacht Bewegung',
      'arming': 'Wird scharfgestellt... bitte still halten',
      'alarm_active': 'Bewegung erkannt!',
      'idle': 'Bereit zum Scharfstellen',
      'stop_alarm': 'Alarm stoppen',
      'delta': 'Delta',
      'delay_label': 'Verzögerung: @n s',
      'sensitivity': 'Empfindlichkeit',
      'sensitivity_low': 'Niedrig',
      'sensitivity_medium': 'Mittel',
      'sensitivity_high': 'Hoch',
      'sensitivity_low_desc':
          'Löst nur bei starkem Schubsen oder Anheben aus',
      'sensitivity_medium_desc':
          'Ausgewogen — reagiert auf normales Anstoßen',
      'sensitivity_high_desc':
          'Reagiert auf kleinste Berührung oder Vibration',
      'arm': 'Scharf',
      'disarm': 'Entschärfen',
      'dismiss_alarm': 'Alarm beenden',
      'state_disarmed': 'ENTSCHÄRFT',
      'state_arming': 'AKTIVIEREN',
      'state_armed': 'SCHARF',
      'state_alarm': 'ALARM',
      'dial_hint_disarmed': 'Tippen zum Scharfstellen',
      'dial_hint_arming': 'Telefon ruhig halten',
      'dial_hint_armed': 'Überwacht Bewegung',
      'dial_hint_alarm': 'Unten tippen zum Beenden',
      'retry': 'Erneut',
      'sensor_retry_hint': 'Tippe auf Scharf, um es erneut zu versuchen',
      'alarm_sound': 'Alarmton',
      'sound_siren': 'Sirene',
      'sound_beep': 'Piepton',
      'more_settings': 'Mehr',
      'detection_section': 'Erkennung',
      'alarm_section': 'Alarm',
      'about_section': 'Über',
      'delay_desc': 'Zeit, um das Telefon vor dem Scharfstellen abzulegen',
      'haptics': 'Vibration',
      'haptics_desc': 'Telefon während des Alarms vibrieren lassen',
      'test_alarm': 'Alarm testen',
      'settings_locked':
          'Beende die Sitzung, um diese Einstellungen zu ändern',
      'version': 'Version',
      'popular': 'Beliebt',
      'motion_detected': 'Bewegung erkannt',
      'delta_value': 'Delta @n',
      'how_to_use': 'Verwendung',
      'step_settings': 'Verzögerung und Empfindlichkeit einstellen',
      'step_place': 'Start tippen und das Telefon ruhig liegen lassen',
      'step_stop': 'Sitzung selbst stoppen, um den Alarm zu beenden',
      'onboarding_skip': 'Überspringen',
      'onboarding_next': 'Weiter',
      'onboarding_get_started': 'Loslegen',
      'onboarding_intro_title': 'Bewegungsalarm für die Tasche',
      'onboarding_intro_desc':
          'Erkennt Bewegung und spielt einen Alarm ab, wenn jemand deine Tasche oder dein Telefon berührt.',
      'onboarding_how_title': 'Verzögerung und Empfindlichkeit einstellen',
      'onboarding_how_desc':
          'Wähle die Wartezeit vor dem Scharfstellen und die Empfindlichkeit der Bewegungserkennung.',
      'onboarding_ready_title': 'Bereit zum Bewachen',
      'onboarding_ready_desc':
          'Lege das Telefon ab, tippe Start, und der Alarm überwacht Bewegungen.',
      'onboarding_privacy_note':
          'Läuft vollständig auf dem Gerät. Kein Konto und keine besonderen Berechtigungen.',
      'premium': 'Premium',
      'premium_title': 'App unterstützen',
      'premium_subtitle': 'Werbung mit einem einmaligen Trinkgeld entfernen',
      'premium_unlocked': 'Premium aktiv. Danke!',
      'premium_purchase': 'Premium kaufen',
      'premium_restore': 'Kauf wiederherstellen',
      'premium_loading': 'Lädt...',
      'premium_store_unavailable': 'Store nicht verfügbar',
      'premium_option_small_title': 'Kaffee-Tipp',
      'premium_option_small_desc': 'Werbung entfernen',
      'premium_option_medium_title': 'Mittagessen',
      'premium_option_medium_desc': 'Werbung entfernen (beliebt)',
      'premium_option_large_title': 'Volle Unterstützung',
      'premium_option_large_desc': 'Werbung entfernen + danke!',
      'premium_benefit_no_ads': 'Keine Werbung',
      'premium_benefit_no_ads_desc': 'Werbefreie Nutzung genießen',
      'premium_benefit_lifetime': 'Lebenslang',
      'premium_benefit_lifetime_desc': 'Einmalig, keine Abos',
      'premium_benefit_support': 'Entwickler unterstützen',
      'premium_benefit_support_desc': 'Hilft, die App am Leben zu halten',
      'premium_benefit_peace': 'Gelassenheit',
      'premium_benefit_peace_desc': 'Konzentriere dich auf Wichtiges',
      'remove_ads_cta': 'Werbung entfernen · Entwickler unterstützen',
      'premium_one_time_note': 'Einmaliger Kauf · Kein Abo',
      'premium_benefits_title': 'Das bekommst du',
    },

    // Русский
    'ru': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Старт',
      'stop': 'Стоп',
      'settings': 'Настройки',
      'history': 'История',
      'no_history': 'Локальной истории пока нет',
      'sensor_unavailable': 'Сенсор недоступен на этом устройстве',
      'policy_note':
          'Только для развлечения и локального использования. Обнаружение не гарантируется.',
      'armed': 'Включено - отслеживание движения',
      'arming': 'Подготовка... не двигайте телефон',
      'alarm_active': 'Движение обнаружено!',
      'idle': 'Готово к запуску',
      'stop_alarm': 'Остановить сигнал',
      'delta': 'Дельта',
      'delay_label': 'Задержка: @n с',
      'sensitivity': 'Чувствительность',
      'sensitivity_low': 'Низкая',
      'sensitivity_medium': 'Средняя',
      'sensitivity_high': 'Высокая',
      'sensitivity_low_desc':
          'Срабатывает только при сильном толчке или поднятии',
      'sensitivity_medium_desc':
          'Баланс — реагирует на обычный толчок',
      'sensitivity_high_desc':
          'Реагирует на малейшее касание или вибрацию',
      'arm': 'Включить',
      'disarm': 'Выключить',
      'dismiss_alarm': 'Отключить сигнал',
      'state_disarmed': 'ВЫКЛ',
      'state_arming': 'АКТИВАЦИЯ',
      'state_armed': 'ОХРАНА',
      'state_alarm': 'ТРЕВОГА',
      'dial_hint_disarmed': 'Нажмите для включения',
      'dial_hint_arming': 'Держите телефон неподвижно',
      'dial_hint_armed': 'Отслеживание движения',
      'dial_hint_alarm': 'Нажмите ниже, чтобы отключить',
      'retry': 'Повтор',
      'sensor_retry_hint': 'Нажмите «Включить», чтобы повторить',
      'alarm_sound': 'Звук сигнала',
      'sound_siren': 'Сирена',
      'sound_beep': 'Бип',
      'more_settings': 'Ещё',
      'detection_section': 'Обнаружение',
      'alarm_section': 'Сигнал',
      'about_section': 'О приложении',
      'delay_desc': 'Время, чтобы положить телефон до включения',
      'haptics': 'Вибрация',
      'haptics_desc': 'Вибрация телефона во время сигнала',
      'test_alarm': 'Проверить сигнал',
      'settings_locked': 'Остановите сеанс, чтобы изменить эти настройки',
      'version': 'Версия',
      'popular': 'Популярно',
      'motion_detected': 'Движение обнаружено',
      'delta_value': 'Дельта @n',
      'how_to_use': 'Как использовать',
      'step_settings': 'Настройте задержку и чувствительность',
      'step_place': 'Нажмите Старт и оставьте телефон неподвижным',
      'step_stop': 'Остановите сеанс вручную, чтобы выключить сигнал',
      'onboarding_skip': 'Пропустить',
      'onboarding_next': 'Далее',
      'onboarding_get_started': 'Начать',
      'onboarding_intro_title': 'Карманная сигнализация движения',
      'onboarding_intro_desc':
          'Обнаруживает движение и включает сигнал, когда кто-то трогает вашу сумку или телефон.',
      'onboarding_how_title': 'Настройте задержку и чувствительность',
      'onboarding_how_desc':
          'Выберите время до включения охраны и чувствительность обнаружения движения.',
      'onboarding_ready_title': 'Готово к охране',
      'onboarding_ready_desc':
          'Положите телефон, нажмите Старт, и сигнализация будет следить за движением.',
      'onboarding_privacy_note':
          'Работает полностью на устройстве. Аккаунт и особые разрешения не нужны.',
      'premium': 'Премиум',
      'premium_title': 'Поддержать приложение',
      'premium_subtitle': 'Уберите рекламу разовым взносом',
      'premium_unlocked': 'Премиум активен. Спасибо!',
      'premium_purchase': 'Купить Премиум',
      'premium_restore': 'Восстановить покупку',
      'premium_loading': 'Загрузка...',
      'premium_store_unavailable': 'Магазин недоступен',
      'premium_option_small_title': 'Кофе',
      'premium_option_small_desc': 'Удалить рекламу',
      'premium_option_medium_title': 'Обед',
      'premium_option_medium_desc': 'Удалить рекламу (популярно)',
      'premium_option_large_title': 'Полная поддержка',
      'premium_option_large_desc': 'Удалить рекламу + спасибо!',
      'premium_benefit_no_ads': 'Без рекламы',
      'premium_benefit_no_ads_desc': 'Используйте приложение без рекламы',
      'premium_benefit_lifetime': 'Навсегда',
      'premium_benefit_lifetime_desc': 'Разово, без подписок',
      'premium_benefit_support': 'Поддержка автора',
      'premium_benefit_support_desc': 'Помогите приложению развиваться',
      'premium_benefit_peace': 'Спокойствие',
      'premium_benefit_peace_desc': 'Сосредоточьтесь на важном',
      'remove_ads_cta': 'Убрать рекламу · Поддержать разработчика',
      'premium_one_time_note': 'Разовая покупка · Без подписки',
      'premium_benefits_title': 'Что вы получаете',
    },

    // Français
    'fr': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Démarrer',
      'stop': 'Arrêter',
      'settings': 'Réglages',
      'history': 'Historique',
      'no_history': 'Aucun historique local pour le moment',
      'sensor_unavailable': 'Capteur indisponible sur cet appareil',
      'policy_note':
          'Usage local et divertissement uniquement. La détection n’est pas garantie.',
      'armed': 'Armé - surveillance des mouvements',
      'arming': 'Armement... gardez le téléphone immobile',
      'alarm_active': 'Mouvement détecté !',
      'idle': 'Prêt à être armé',
      'stop_alarm': 'Arrêter l’alarme',
      'delta': 'Delta',
      'delay_label': 'Délai : @n s',
      'sensitivity': 'Sensibilité',
      'sensitivity_low': 'Faible',
      'sensitivity_medium': 'Moyenne',
      'sensitivity_high': 'Élevée',
      'sensitivity_low_desc':
          'Se déclenche seulement en cas de forte poussée',
      'sensitivity_medium_desc':
          'Équilibré — réagit à une secousse normale',
      'sensitivity_high_desc':
          'Réagit au moindre contact ou à la vibration',
      'arm': 'Armer',
      'disarm': 'Désarmer',
      'dismiss_alarm': 'Arrêter l’alarme',
      'state_disarmed': 'DÉSARMÉ',
      'state_arming': 'ARMEMENT',
      'state_armed': 'ARMÉ',
      'state_alarm': 'ALARME',
      'dial_hint_disarmed': 'Touchez pour armer',
      'dial_hint_arming': 'Gardez le téléphone immobile',
      'dial_hint_armed': 'Surveille les mouvements',
      'dial_hint_alarm': 'Touchez en bas pour arrêter',
      'retry': 'Réessayer',
      'sensor_retry_hint': 'Touchez Armer pour réessayer',
      'alarm_sound': 'Son d’alarme',
      'sound_siren': 'Sirène',
      'sound_beep': 'Bip',
      'more_settings': 'Plus',
      'detection_section': 'Détection',
      'alarm_section': 'Alarme',
      'about_section': 'À propos',
      'delay_desc': 'Temps pour poser le téléphone avant l’armement',
      'haptics': 'Vibration',
      'haptics_desc': 'Faire vibrer le téléphone pendant l’alarme',
      'test_alarm': 'Tester l’alarme',
      'settings_locked':
          'Arrêtez la session pour modifier ces réglages',
      'version': 'Version',
      'popular': 'Populaire',
      'motion_detected': 'Mouvement détecté',
      'delta_value': 'Delta @n',
      'how_to_use': 'Utilisation',
      'step_settings': 'Réglez le délai et la sensibilité',
      'step_place': 'Touchez Démarrer, puis gardez le téléphone immobile',
      'step_stop': 'Arrêtez vous-même la session pour couper l’alarme',
      'onboarding_skip': 'Passer',
      'onboarding_next': 'Suivant',
      'onboarding_get_started': 'Commencer',
      'onboarding_intro_title': 'Alarme de mouvement de poche',
      'onboarding_intro_desc':
          'Détecte les mouvements et déclenche une alarme quand quelqu’un touche votre sac ou votre téléphone.',
      'onboarding_how_title': 'Réglez le délai et la sensibilité',
      'onboarding_how_desc':
          'Choisissez le temps avant l’armement et la sensibilité de détection des mouvements.',
      'onboarding_ready_title': 'Prêt à surveiller',
      'onboarding_ready_desc':
          'Posez le téléphone, touchez Démarrer, et l’alarme surveille les mouvements.',
      'onboarding_privacy_note':
          'Fonctionne entièrement sur l’appareil. Aucun compte ni autorisation spéciale.',
      'premium': 'Premium',
      'premium_title': 'Soutenir l’app',
      'premium_subtitle': 'Supprimez les pubs avec un don unique',
      'premium_unlocked': 'Premium actif. Merci !',
      'premium_purchase': 'Obtenir Premium',
      'premium_restore': 'Restaurer l’achat',
      'premium_loading': 'Chargement...',
      'premium_store_unavailable': 'Boutique indisponible',
      'premium_option_small_title': 'Café',
      'premium_option_small_desc': 'Supprimer les pubs',
      'premium_option_medium_title': 'Déjeuner',
      'premium_option_medium_desc': 'Supprimer les pubs (populaire)',
      'premium_option_large_title': 'Soutien complet',
      'premium_option_large_desc': 'Supprimer les pubs + merci !',
      'premium_benefit_no_ads': 'Sans pubs',
      'premium_benefit_no_ads_desc': 'Profitez d’une expérience sans pub',
      'premium_benefit_lifetime': 'À vie',
      'premium_benefit_lifetime_desc': 'Paiement unique, sans abonnement',
      'premium_benefit_support': 'Soutenir le dev',
      'premium_benefit_support_desc': 'Aidez l’app à continuer',
      'premium_benefit_peace': 'Tranquillité',
      'premium_benefit_peace_desc': 'Concentrez-vous sur l’essentiel',
      'remove_ads_cta': 'Supprimer les pubs · Soutenir le développeur',
      'premium_one_time_note': 'Achat unique · Sans abonnement',
      'premium_benefits_title': 'Ce que vous obtenez',
    },

    // Español
    'es': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Iniciar',
      'stop': 'Detener',
      'settings': 'Ajustes',
      'history': 'Historial',
      'no_history': 'Aún no hay historial local',
      'sensor_unavailable': 'Sensor no disponible en este dispositivo',
      'policy_note':
          'Solo para entretenimiento y uso local. La detección no está garantizada.',
      'armed': 'Activada - vigilando movimiento',
      'arming': 'Activando... mantén el teléfono quieto',
      'alarm_active': '¡Movimiento detectado!',
      'idle': 'Lista para activar',
      'stop_alarm': 'Detener alarma',
      'delta': 'Delta',
      'delay_label': 'Retraso: @n s',
      'sensitivity': 'Sensibilidad',
      'sensitivity_low': 'Baja',
      'sensitivity_medium': 'Media',
      'sensitivity_high': 'Alta',
      'sensitivity_low_desc':
          'Se activa solo con un empujón fuerte o al levantar',
      'sensitivity_medium_desc':
          'Equilibrado — reacciona a un movimiento normal',
      'sensitivity_high_desc':
          'Reacciona al menor toque o vibración',
      'arm': 'Activar',
      'disarm': 'Desactivar',
      'dismiss_alarm': 'Detener alarma',
      'state_disarmed': 'DESACTIVADA',
      'state_arming': 'ACTIVANDO',
      'state_armed': 'ACTIVADA',
      'state_alarm': 'ALARMA',
      'dial_hint_disarmed': 'Toca para activar',
      'dial_hint_arming': 'Mantén el teléfono quieto',
      'dial_hint_armed': 'Vigilando movimiento',
      'dial_hint_alarm': 'Toca abajo para detener',
      'retry': 'Reintentar',
      'sensor_retry_hint': 'Toca Activar para reintentar',
      'alarm_sound': 'Sonido de alarma',
      'sound_siren': 'Sirena',
      'sound_beep': 'Pitido',
      'more_settings': 'Más',
      'detection_section': 'Detección',
      'alarm_section': 'Alarma',
      'about_section': 'Acerca de',
      'delay_desc': 'Tiempo para colocar el teléfono antes de activar',
      'haptics': 'Vibración',
      'haptics_desc': 'Vibrar el teléfono mientras suena la alarma',
      'test_alarm': 'Probar alarma',
      'settings_locked':
          'Detén la sesión para cambiar estos ajustes',
      'version': 'Versión',
      'popular': 'Popular',
      'motion_detected': 'Movimiento detectado',
      'delta_value': 'Delta @n',
      'how_to_use': 'Cómo usar',
      'step_settings': 'Configura el retraso y la sensibilidad',
      'step_place': 'Toca Iniciar y deja el teléfono quieto',
      'step_stop': 'Detén la sesión tú mismo para silenciar',
      'onboarding_skip': 'Omitir',
      'onboarding_next': 'Siguiente',
      'onboarding_get_started': 'Comenzar',
      'onboarding_intro_title': 'Alarma de movimiento de bolsillo',
      'onboarding_intro_desc':
          'Detecta movimiento y hace sonar una alarma cuando alguien toca tu bolso o teléfono.',
      'onboarding_how_title': 'Configura retraso y sensibilidad',
      'onboarding_how_desc':
          'Elige cuánto esperar antes de activar y qué tan sensible será la detección.',
      'onboarding_ready_title': 'Lista para vigilar',
      'onboarding_ready_desc':
          'Coloca el teléfono, toca Iniciar y la alarma vigilará el movimiento.',
      'onboarding_privacy_note':
          'Funciona completamente en el dispositivo. Sin cuenta ni permisos especiales.',
      'premium': 'Premium',
      'premium_title': 'Apoya la app',
      'premium_subtitle': 'Quita anuncios con un aporte único',
      'premium_unlocked': 'Premium activo. ¡Gracias!',
      'premium_purchase': 'Obtener Premium',
      'premium_restore': 'Restaurar compra',
      'premium_loading': 'Cargando...',
      'premium_store_unavailable': 'Tienda no disponible',
      'premium_option_small_title': 'Café',
      'premium_option_small_desc': 'Quitar anuncios',
      'premium_option_medium_title': 'Almuerzo',
      'premium_option_medium_desc': 'Quitar anuncios (popular)',
      'premium_option_large_title': 'Apoyo completo',
      'premium_option_large_desc': 'Quitar anuncios + ¡gracias!',
      'premium_benefit_no_ads': 'Sin anuncios',
      'premium_benefit_no_ads_desc': 'Disfruta una experiencia sin anuncios',
      'premium_benefit_lifetime': 'De por vida',
      'premium_benefit_lifetime_desc': 'Una vez, sin suscripciones',
      'premium_benefit_support': 'Apoya al dev',
      'premium_benefit_support_desc': 'Ayuda a mantener viva la app',
      'premium_benefit_peace': 'Tranquilidad',
      'premium_benefit_peace_desc': 'Concéntrate en lo importante',
      'remove_ads_cta': 'Quitar anuncios · Apoyar al desarrollador',
      'premium_one_time_note': 'Compra única · Sin suscripción',
      'premium_benefits_title': 'Lo que obtienes',
    },

    // Português
    'pt': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Iniciar',
      'stop': 'Parar',
      'settings': 'Configurações',
      'history': 'Histórico',
      'no_history': 'Ainda não há histórico local',
      'sensor_unavailable': 'Sensor indisponível neste dispositivo',
      'policy_note':
          'Apenas para entretenimento e uso local. A detecção não é garantida.',
      'armed': 'Armado - monitorando movimento',
      'arming': 'Armando... mantenha o telefone parado',
      'alarm_active': 'Movimento detectado!',
      'idle': 'Pronto para armar',
      'stop_alarm': 'Parar alarme',
      'delta': 'Delta',
      'delay_label': 'Atraso: @n s',
      'sensitivity': 'Sensibilidade',
      'sensitivity_low': 'Baixa',
      'sensitivity_medium': 'Média',
      'sensitivity_high': 'Alta',
      'sensitivity_low_desc':
          'Dispara apenas com empurrão forte ou ao levantar',
      'sensitivity_medium_desc':
          'Equilibrado — reage a um toque normal',
      'sensitivity_high_desc':
          'Reage ao menor toque ou vibração',
      'arm': 'Armar',
      'disarm': 'Desarmar',
      'dismiss_alarm': 'Parar alarme',
      'state_disarmed': 'DESARMADO',
      'state_arming': 'ARMANDO',
      'state_armed': 'ARMADO',
      'state_alarm': 'ALARME',
      'dial_hint_disarmed': 'Toque para armar',
      'dial_hint_arming': 'Mantenha o telefone parado',
      'dial_hint_armed': 'Monitorando movimento',
      'dial_hint_alarm': 'Toque abaixo para parar',
      'retry': 'Tentar de novo',
      'sensor_retry_hint': 'Toque em Armar para tentar de novo',
      'alarm_sound': 'Som do alarme',
      'sound_siren': 'Sirene',
      'sound_beep': 'Bipe',
      'more_settings': 'Mais',
      'detection_section': 'Detecção',
      'alarm_section': 'Alarme',
      'about_section': 'Sobre',
      'delay_desc': 'Tempo para posicionar o telefone antes de armar',
      'haptics': 'Vibração',
      'haptics_desc': 'Vibrar o telefone enquanto o alarme toca',
      'test_alarm': 'Testar alarme',
      'settings_locked':
          'Pare a sessão para alterar estas configurações',
      'version': 'Versão',
      'popular': 'Popular',
      'motion_detected': 'Movimento detectado',
      'delta_value': 'Delta @n',
      'how_to_use': 'Como usar',
      'step_settings': 'Defina atraso e sensibilidade',
      'step_place': 'Toque em Iniciar e mantenha o telefone parado',
      'step_stop': 'Pare a sessão manualmente para silenciar',
      'onboarding_skip': 'Pular',
      'onboarding_next': 'Avançar',
      'onboarding_get_started': 'Começar',
      'onboarding_intro_title': 'Alarme de movimento de bolso',
      'onboarding_intro_desc':
          'Detecta movimento e toca um alarme quando alguém toca na sua bolsa ou telefone.',
      'onboarding_how_title': 'Defina atraso e sensibilidade',
      'onboarding_how_desc':
          'Escolha quanto esperar antes de armar e a sensibilidade da detecção de movimento.',
      'onboarding_ready_title': 'Pronto para vigiar',
      'onboarding_ready_desc':
          'Coloque o telefone, toque em Iniciar e o alarme monitora o movimento.',
      'onboarding_privacy_note':
          'Funciona totalmente no dispositivo. Sem conta ou permissões especiais.',
      'premium': 'Premium',
      'premium_title': 'Apoie o app',
      'premium_subtitle': 'Remova anúncios com uma contribuição única',
      'premium_unlocked': 'Premium ativo. Obrigado!',
      'premium_purchase': 'Obter Premium',
      'premium_restore': 'Restaurar compra',
      'premium_loading': 'Carregando...',
      'premium_store_unavailable': 'Loja indisponível',
      'premium_option_small_title': 'Café',
      'premium_option_small_desc': 'Remover anúncios',
      'premium_option_medium_title': 'Almoço',
      'premium_option_medium_desc': 'Remover anúncios (popular)',
      'premium_option_large_title': 'Apoio completo',
      'premium_option_large_desc': 'Remover anúncios + obrigado!',
      'premium_benefit_no_ads': 'Sem anúncios',
      'premium_benefit_no_ads_desc': 'Aproveite sem anúncios',
      'premium_benefit_lifetime': 'Vitalício',
      'premium_benefit_lifetime_desc': 'Pagamento único, sem assinatura',
      'premium_benefit_support': 'Apoiar dev',
      'premium_benefit_support_desc': 'Ajude a manter o app vivo',
      'premium_benefit_peace': 'Tranquilidade',
      'premium_benefit_peace_desc': 'Foque no que importa',
      'remove_ads_cta': 'Remover anúncios · Apoiar desenvolvedor',
      'premium_one_time_note': 'Compra única · Sem assinatura',
      'premium_benefits_title': 'O que você recebe',
    },

    // Bahasa Indonesia
    'id': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'Mulai',
      'stop': 'Berhenti',
      'settings': 'Pengaturan',
      'history': 'Riwayat',
      'no_history': 'Belum ada riwayat lokal',
      'sensor_unavailable': 'Sensor tidak tersedia di perangkat ini',
      'policy_note':
          'Hanya untuk hiburan dan penggunaan lokal. Deteksi tidak dijamin.',
      'armed': 'Aktif - memantau gerakan',
      'arming': 'Menyiapkan... jangan gerakkan ponsel',
      'alarm_active': 'Gerakan terdeteksi!',
      'idle': 'Siap diaktifkan',
      'stop_alarm': 'Hentikan Alarm',
      'delta': 'Delta',
      'delay_label': 'Jeda: @n dtk',
      'sensitivity': 'Sensitivitas',
      'sensitivity_low': 'Rendah',
      'sensitivity_medium': 'Sedang',
      'sensitivity_high': 'Tinggi',
      'sensitivity_low_desc':
          'Aktif hanya saat didorong kuat atau diangkat',
      'sensitivity_medium_desc':
          'Seimbang — bereaksi terhadap sentuhan biasa',
      'sensitivity_high_desc':
          'Bereaksi terhadap sentuhan atau getaran sekecil apa pun',
      'arm': 'Aktifkan',
      'disarm': 'Nonaktifkan',
      'dismiss_alarm': 'Hentikan Alarm',
      'state_disarmed': 'NONAKTIF',
      'state_arming': 'MENGAKTIFKAN',
      'state_armed': 'AKTIF',
      'state_alarm': 'ALARM',
      'dial_hint_disarmed': 'Ketuk untuk mengaktifkan',
      'dial_hint_arming': 'Jaga ponsel tetap diam',
      'dial_hint_armed': 'Memantau gerakan',
      'dial_hint_alarm': 'Ketuk di bawah untuk menghentikan',
      'retry': 'Coba lagi',
      'sensor_retry_hint': 'Ketuk Aktifkan untuk mencoba lagi',
      'alarm_sound': 'Suara alarm',
      'sound_siren': 'Sirene',
      'sound_beep': 'Bip',
      'more_settings': 'Lainnya',
      'detection_section': 'Deteksi',
      'alarm_section': 'Alarm',
      'about_section': 'Tentang',
      'delay_desc': 'Waktu untuk meletakkan ponsel sebelum aktif',
      'haptics': 'Getaran',
      'haptics_desc': 'Getarkan ponsel saat alarm berbunyi',
      'test_alarm': 'Uji alarm',
      'settings_locked':
          'Hentikan sesi untuk mengubah pengaturan ini',
      'version': 'Versi',
      'popular': 'Populer',
      'motion_detected': 'Gerakan terdeteksi',
      'delta_value': 'Delta @n',
      'how_to_use': 'Cara Menggunakan',
      'step_settings': 'Atur jeda dan sensitivitas',
      'step_place': 'Ketuk Mulai, lalu biarkan ponsel tetap diam',
      'step_stop': 'Hentikan sesi sendiri untuk mematikan alarm',
      'onboarding_skip': 'Lewati',
      'onboarding_next': 'Berikutnya',
      'onboarding_get_started': 'Mulai',
      'onboarding_intro_title': 'Alarm gerak saku',
      'onboarding_intro_desc':
          'Mendeteksi gerakan dan membunyikan alarm saat seseorang menyentuh tas atau ponsel Anda.',
      'onboarding_how_title': 'Atur jeda dan sensitivitas',
      'onboarding_how_desc':
          'Pilih waktu tunggu sebelum aktif dan seberapa sensitif deteksi gerakan.',
      'onboarding_ready_title': 'Siap menjaga',
      'onboarding_ready_desc':
          'Letakkan ponsel, ketuk Mulai, dan alarm memantau gerakan.',
      'onboarding_privacy_note':
          'Berjalan sepenuhnya di perangkat. Tanpa akun atau izin khusus.',
      'premium': 'Premium',
      'premium_title': 'Dukung Aplikasi',
      'premium_subtitle': 'Hapus iklan dengan dukungan satu kali',
      'premium_unlocked': 'Premium aktif. Terima kasih!',
      'premium_purchase': 'Dapatkan Premium',
      'premium_restore': 'Pulihkan pembelian',
      'premium_loading': 'Memuat...',
      'premium_store_unavailable': 'Toko tidak tersedia',
      'premium_option_small_title': 'Tip Kopi',
      'premium_option_small_desc': 'Hapus iklan',
      'premium_option_medium_title': 'Traktir Makan Siang',
      'premium_option_medium_desc': 'Hapus iklan (populer)',
      'premium_option_large_title': 'Dukungan Penuh',
      'premium_option_large_desc': 'Hapus iklan + terima kasih!',
      'premium_benefit_no_ads': 'Tanpa Iklan',
      'premium_benefit_no_ads_desc': 'Nikmati pengalaman tanpa iklan',
      'premium_benefit_lifetime': 'Seumur Hidup',
      'premium_benefit_lifetime_desc': 'Sekali bayar, tanpa langganan',
      'premium_benefit_support': 'Dukung Dev',
      'premium_benefit_support_desc': 'Bantu menjaga aplikasi tetap hidup',
      'premium_benefit_peace': 'Tenang',
      'premium_benefit_peace_desc': 'Fokus pada yang penting',
      'remove_ads_cta': 'Hapus iklan · Dukung pengembang',
      'premium_one_time_note': 'Pembelian satu kali · Tanpa langganan',
      'premium_benefits_title': 'Yang Anda dapatkan',
    },

    // 中文（简体）
    'zh': {
      'app_title': 'Motion Alarm Pocket',
      'start': '开始',
      'stop': '停止',
      'settings': '设置',
      'history': '历史',
      'no_history': '暂无本地历史',
      'sensor_unavailable': '此设备上的传感器不可用',
      'policy_note': '仅供娱乐和本地使用。不保证检测结果。',
      'armed': '已布防 - 正在监测移动',
      'arming': '正在布防... 请保持静止',
      'alarm_active': '检测到移动！',
      'idle': '准备布防',
      'stop_alarm': '停止警报',
      'delta': '变化量',
      'delay_label': '延迟：@n 秒',
      'sensitivity': '灵敏度',
      'sensitivity_low': '低',
      'sensitivity_medium': '中',
      'sensitivity_high': '高',
      'sensitivity_low_desc': '仅在用力推动或拿起时触发',
      'sensitivity_medium_desc': '均衡 — 对普通触碰作出反应',
      'sensitivity_high_desc': '对最轻微的触碰或振动也会反应',
      'arm': '布防',
      'disarm': '撤防',
      'dismiss_alarm': '关闭警报',
      'state_disarmed': '已撤防',
      'state_arming': '布防中',
      'state_armed': '已布防',
      'state_alarm': '警报',
      'dial_hint_disarmed': '点击布防',
      'dial_hint_arming': '请保持手机静止',
      'dial_hint_armed': '正在监测移动',
      'dial_hint_alarm': '点击下方关闭',
      'retry': '重试',
      'sensor_retry_hint': '点击布防重试',
      'alarm_sound': '警报声',
      'sound_siren': '警笛',
      'sound_beep': '哔声',
      'more_settings': '更多',
      'detection_section': '检测',
      'alarm_section': '警报',
      'about_section': '关于',
      'delay_desc': '布防前放置手机的时间',
      'haptics': '振动',
      'haptics_desc': '警报响起时使手机振动',
      'test_alarm': '测试警报',
      'settings_locked': '停止会话以更改这些设置',
      'version': '版本',
      'popular': '热门',
      'motion_detected': '检测到移动',
      'delta_value': '变化量 @n',
      'how_to_use': '使用方法',
      'step_settings': '设置延迟和灵敏度',
      'step_place': '点击开始，然后保持手机静止',
      'step_stop': '请手动停止会话以静音',
      'onboarding_skip': '跳过',
      'onboarding_next': '下一步',
      'onboarding_get_started': '开始使用',
      'onboarding_intro_title': '口袋移动警报',
      'onboarding_intro_desc': '当有人触碰你的包或手机时，检测移动并响起警报。',
      'onboarding_how_title': '设置延迟和灵敏度',
      'onboarding_how_desc': '选择布防前等待多久，以及移动检测的灵敏度。',
      'onboarding_ready_title': '准备守护',
      'onboarding_ready_desc': '放下手机，点击开始，警报将监测移动。',
      'onboarding_privacy_note': '完全在设备上运行。无需账号或特殊权限。',
      'premium': '高级版',
      'premium_title': '支持应用',
      'premium_subtitle': '一次性支持即可移除广告',
      'premium_unlocked': '高级版已激活。谢谢！',
      'premium_purchase': '获取高级版',
      'premium_restore': '恢复购买',
      'premium_loading': '加载中...',
      'premium_store_unavailable': '商店不可用',
      'premium_option_small_title': '咖啡支持',
      'premium_option_small_desc': '移除广告',
      'premium_option_medium_title': '午餐支持',
      'premium_option_medium_desc': '移除广告（热门）',
      'premium_option_large_title': '全力支持',
      'premium_option_large_desc': '移除广告 + 感谢！',
      'premium_benefit_no_ads': '无广告',
      'premium_benefit_no_ads_desc': '享受无广告体验',
      'premium_benefit_lifetime': '终身',
      'premium_benefit_lifetime_desc': '一次购买，无订阅',
      'premium_benefit_support': '支持开发者',
      'premium_benefit_support_desc': '帮助应用持续维护',
      'premium_benefit_peace': '安心',
      'premium_benefit_peace_desc': '专注重要事情',
      'remove_ads_cta': '移除广告 · 支持开发者',
      'premium_one_time_note': '一次性购买 · 无订阅',
      'premium_benefits_title': '你将获得',
    },

    // العربية
    'ar': {
      'app_title': 'Motion Alarm Pocket',
      'start': 'بدء',
      'stop': 'إيقاف',
      'settings': 'الإعدادات',
      'history': 'السجل',
      'no_history': 'لا يوجد سجل محلي بعد',
      'sensor_unavailable': 'المستشعر غير متاح على هذا الجهاز',
      'policy_note': 'للترفيه والاستخدام المحلي فقط. لا يمكن ضمان الاكتشاف.',
      'armed': 'مفعّل - يراقب الحركة',
      'arming': 'جارٍ التفعيل... أبقِ الهاتف ثابتًا',
      'alarm_active': 'تم اكتشاف حركة!',
      'idle': 'جاهز للتفعيل',
      'stop_alarm': 'إيقاف التنبيه',
      'delta': 'دلتا',
      'delay_label': 'التأخير: @n ث',
      'sensitivity': 'الحساسية',
      'sensitivity_low': 'منخفضة',
      'sensitivity_medium': 'متوسطة',
      'sensitivity_high': 'عالية',
      'sensitivity_low_desc': 'يعمل فقط عند الدفع القوي أو الرفع',
      'sensitivity_medium_desc': 'متوازن — يستجيب للهزة العادية',
      'sensitivity_high_desc': 'يستجيب لأدنى لمسة أو اهتزاز',
      'arm': 'تفعيل',
      'disarm': 'إيقاف',
      'dismiss_alarm': 'إيقاف التنبيه',
      'state_disarmed': 'متوقف',
      'state_arming': 'جارٍ التفعيل',
      'state_armed': 'مفعّل',
      'state_alarm': 'تنبيه',
      'dial_hint_disarmed': 'اضغط للتفعيل',
      'dial_hint_arming': 'أبقِ الهاتف ثابتًا',
      'dial_hint_armed': 'يراقب الحركة',
      'dial_hint_alarm': 'اضغط بالأسفل للإيقاف',
      'retry': 'إعادة المحاولة',
      'sensor_retry_hint': 'اضغط تفعيل لإعادة المحاولة',
      'alarm_sound': 'صوت التنبيه',
      'sound_siren': 'صفارة',
      'sound_beep': 'صافرة',
      'more_settings': 'المزيد',
      'detection_section': 'الاكتشاف',
      'alarm_section': 'التنبيه',
      'about_section': 'حول',
      'delay_desc': 'وقت وضع الهاتف قبل التفعيل',
      'haptics': 'الاهتزاز',
      'haptics_desc': 'اهتزاز الهاتف أثناء التنبيه',
      'test_alarm': 'اختبار التنبيه',
      'settings_locked': 'أوقف الجلسة لتغيير هذه الإعدادات',
      'version': 'الإصدار',
      'popular': 'شائع',
      'motion_detected': 'تم اكتشاف حركة',
      'delta_value': 'دلتا @n',
      'how_to_use': 'طريقة الاستخدام',
      'step_settings': 'اضبط التأخير والحساسية',
      'step_place': 'اضغط بدء، ثم أبقِ الهاتف ثابتًا',
      'step_stop': 'أوقف الجلسة بنفسك لإسكات التنبيه',
      'onboarding_skip': 'تخطٍ',
      'onboarding_next': 'التالي',
      'onboarding_get_started': 'ابدأ',
      'onboarding_intro_title': 'تنبيه حركة للجيب',
      'onboarding_intro_desc':
          'يكتشف الحركة ويطلق تنبيهًا عندما يلمس أحد حقيبتك أو هاتفك.',
      'onboarding_how_title': 'اضبط التأخير والحساسية',
      'onboarding_how_desc':
          'اختر مدة الانتظار قبل التفعيل ومدى حساسية اكتشاف الحركة.',
      'onboarding_ready_title': 'جاهز للحراسة',
      'onboarding_ready_desc': 'ضع الهاتف، اضغط بدء، وسيراقب التنبيه الحركة.',
      'onboarding_privacy_note':
          'يعمل بالكامل على الجهاز. لا حاجة إلى حساب أو أذونات خاصة.',
      'premium': 'بريميوم',
      'premium_title': 'ادعم التطبيق',
      'premium_subtitle': 'أزل الإعلانات بدعم لمرة واحدة',
      'premium_unlocked': 'بريميوم نشط. شكرًا لك!',
      'premium_purchase': 'احصل على بريميوم',
      'premium_restore': 'استعادة الشراء',
      'premium_loading': 'جارٍ التحميل...',
      'premium_store_unavailable': 'المتجر غير متاح',
      'premium_option_small_title': 'قهوة',
      'premium_option_small_desc': 'إزالة الإعلانات',
      'premium_option_medium_title': 'غداء',
      'premium_option_medium_desc': 'إزالة الإعلانات (شائع)',
      'premium_option_large_title': 'دعم كامل',
      'premium_option_large_desc': 'إزالة الإعلانات + شكرًا!',
      'premium_benefit_no_ads': 'بلا إعلانات',
      'premium_benefit_no_ads_desc': 'استمتع بتجربة بلا إعلانات',
      'premium_benefit_lifetime': 'مدى الحياة',
      'premium_benefit_lifetime_desc': 'مرة واحدة، بلا اشتراكات',
      'premium_benefit_support': 'دعم المطور',
      'premium_benefit_support_desc': 'ساعد في بقاء التطبيق',
      'premium_benefit_peace': 'راحة بال',
      'premium_benefit_peace_desc': 'ركز على ما يهم',
      'remove_ads_cta': 'إزالة الإعلانات · دعم المطور',
      'premium_one_time_note': 'شراء لمرة واحدة · بلا اشتراك',
      'premium_benefits_title': 'ما ستحصل عليه',
    },
  };
}
