import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'Motion Alarm Pocket',
          'start': 'Start',
          'stop': 'Stop',
          'settings': 'Settings',
          'history': 'History',
          'no_history': 'No local history yet',
          'sensor_unavailable': 'Sensor unavailable on this device',
          'policy_note':
              'For entertainment and local use only. Detection is not guaranteed.',
          // status
          'armed': 'Armed – watching for motion',
          'arming': 'Arming… stay still',
          'alarm_active': 'Motion Detected!',
          'idle': 'Ready to arm',
          'stop_alarm': 'Stop Alarm',
          'delta': 'Delta',
          // settings labels
          'delay_label': 'Delay: @ns',
          'sensitivity': 'Sensitivity',
          'sensitivity_low': 'Low',
          'sensitivity_medium': 'Medium',
          'sensitivity_high': 'High',
          'popular': 'Popular',
          'motion_detected': 'Motion detected',
          'delta_value': 'Delta @n',
          // how to use
          'how_to_use': 'How to Use',
          'step_settings': 'Set delay and sensitivity',
          'step_place': 'Tap Start, then keep the phone still',
          'step_stop': 'Stop the session yourself to silence',
          // premium
          'premium': 'Premium',
          'premium_title': 'Support the App',
          'premium_subtitle': 'Remove ads with a one-time tip',
          'premium_unlocked': 'Premium active. Thank you!',
          'premium_purchase': 'Get Premium',
          'premium_restore': 'Restore purchase',
          'premium_loading': 'Loading…',
          'premium_store_unavailable': 'Store unavailable',
          'premium_option_small_title': 'Coffee Tip',
          'premium_option_small_desc': 'Remove ads',
          'premium_option_medium_title': 'Lunch Treat',
          'premium_option_medium_desc': 'Remove ads (most popular)',
          'premium_option_large_title': 'Full Support',
          'premium_option_large_desc': 'Remove ads + thank you!',
          'premium_benefit_no_ads': 'No Ads',
          'premium_benefit_no_ads_desc': 'Enjoy an ad-free experience',
          'premium_benefit_lifetime': 'Lifetime',
          'premium_benefit_lifetime_desc': 'One-time, no subscriptions',
          'premium_benefit_support': 'Support Dev',
          'premium_benefit_support_desc': 'Help keep the app alive',
          'premium_benefit_peace': 'Peace of Mind',
          'premium_benefit_peace_desc': 'Focus on what matters',
          'remove_ads_cta': 'Remove ads · Support developer',
          'premium_one_time_note': 'One-time purchase · No subscription',
          'premium_benefits_title': 'What you get',
        },
        'ko_KR': {
          'app_title': 'Motion Alarm Pocket',
          'start': '시작',
          'stop': '중지',
          'settings': '설정',
          'history': '기록',
          'no_history': '아직 로컬 기록이 없습니다',
          'sensor_unavailable': '이 기기에서 센서를 사용할 수 없습니다',
          'policy_note': '엔터테인먼트 및 로컬 용도이며 감지를 보장하지 않습니다.',
          // status
          'armed': '감시 중 – 움직임을 감지합니다',
          'arming': '준비 중… 폰을 가만히 두세요',
          'alarm_active': '움직임 감지됨!',
          'idle': '시작할 준비 완료',
          'stop_alarm': '경보 중지',
          'delta': '변화량',
          // settings labels
          'delay_label': '딜레이: @n초',
          'sensitivity': '감도',
          'sensitivity_low': '낮음',
          'sensitivity_medium': '중간',
          'sensitivity_high': '높음',
          'popular': '인기',
          'motion_detected': '움직임 감지',
          'delta_value': '변화량 @n',
          // how to use
          'how_to_use': '사용 방법',
          'step_settings': '딜레이와 감도를 설정하세요',
          'step_place': '시작을 탭한 후 폰을 가만히 두세요',
          'step_stop': '세션을 직접 중지해야 경보가 꺼집니다',
          // premium
          'premium': '프리미엄',
          'premium_title': '앱 후원하기',
          'premium_subtitle': '일회성 후원으로 광고를 제거하세요',
          'premium_unlocked': '프리미엄 활성화. 감사합니다!',
          'premium_purchase': '프리미엄 구매',
          'premium_restore': '구매 복원',
          'premium_loading': '로딩 중…',
          'premium_store_unavailable': '스토어를 사용할 수 없습니다',
          'premium_option_small_title': '커피 한 잔',
          'premium_option_small_desc': '광고 제거',
          'premium_option_medium_title': '점심 한 끼',
          'premium_option_medium_desc': '광고 제거 (인기)',
          'premium_option_large_title': '풀 서포트',
          'premium_option_large_desc': '광고 제거 + 감사 인사!',
          'premium_benefit_no_ads': '광고 없음',
          'premium_benefit_no_ads_desc': '광고 없는 경험',
          'premium_benefit_lifetime': '평생 이용',
          'premium_benefit_lifetime_desc': '일회성, 구독 없음',
          'premium_benefit_support': '개발자 후원',
          'premium_benefit_support_desc': '앱 유지에 도움',
          'premium_benefit_peace': '안심 사용',
          'premium_benefit_peace_desc': '중요한 것에 집중',
          'remove_ads_cta': '광고 제거 · 개발자 후원',
          'premium_one_time_note': '일회성 구매 · 구독 없음',
          'premium_benefits_title': '프리미엄 혜택',
        },
      };
}
